# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      
  categories:
    - title: '🛠 Breaking Changes'
      labels:
        - major
        - breaking-change
        
    - title: '🚀 Features'
      labels:
        - minor
        - feature
        - enhancement
        
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
        
    - title: '🧰 Maintenance'
      label: 'chore'
